// File: dffa.v
// Generated by MyHDL 0.11.49
// Date: Thu Oct 31 09:12:43 2024


`timescale 1ns/10ps

module dffa (
    q,
    d,
    clk,
    rst
);


output q;
reg q;
input d;
input clk;
input rst;




always @(posedge clk, negedge rst) begin: DFFA_LOGIC
    if (rst == 0) begin
        q <= 0;
    end
    else begin
        if ((rst == 0)) begin
            q <= 0;
        end
        else begin
            q <= d;
        end
    end
end

endmodule
